metadata(
  :name        => 'MySQL Cluster',
  :description => 'Agent for managing MySQL instances in a cluster',
  :author      => 'Mike Marion',
  :version     => '0.0.2',
  :url         => 'https://www.github.com/BLC/mcollective',
  :license     => '',
  :timeout     => 60
)

action 'promote', :description => 'Makes the MySQL instance a master server' do
  input :yaml_file,
    :prompt      => 'YAML file path',
    :description => 'Path to the YAML fact file',
    :type        => :string,
    :validation  => /.*/,
    :maxlength   => 0,
    :optional    => true

  output :server_id,
    :description => 'The newly assigned server ID',
    :display_as => 'Server ID'
end

action 'enslave', :description => 'Makes the MySQL instance a slave server' do
  input :yaml_file,
    :prompt      => 'YAML file path',
    :description => 'Path to the YAML fact file',
    :type        => :string,
    :validation  => /.*/,
    :maxlength   => 0,
    :optional    => true

  input :master_status_file,
    :prompt      => 'Master status file',
    :description => 'The path to the file generated by ec2-consistent-snapshot containing master status information (/etc/mysql/MASTER_STATUS)',
    :type        => :string,
    :validation  => /.*/,
    :maxlength   => 0,
    :optional    => true

  input :master_hostname
    :prompt      => 'Master hostname',
    :description => 'The hostname of the cluster master (defaults to a fact lookup)',
    :type        => :string,
    :validation  => /.*/,
    :maxlength   => 0,
    :optional    => true

  input :repl_user,
    :prompt      => 'Replication user',
    :description => "The username for the master's replication user",
    :type        => :string,
    :validation  => /.*/,
    :maxlength   => 0,
    :optional    => false

  input :repl_password,
    :prompt      => 'Replication password',
    :description => "The password for the master's replication user",
    :type        => :string,
    :validation  => /.*/,
    :maxlength   => 0,
    :optional    => false

  input :root_password,
    :prompt      => 'Root password',
    :description => "The password for the slave's root user, if applicable",
    :type        => :string,
    :validation  => /.*/,
    :maxlength   => 0,
    :optional    => true

  output :server_id,
    :description => 'The newly assigned server ID',
    :display_as => 'Server ID'
end
